<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7NM1d6\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7NM1d6/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerC7NM1d6.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerC7NM1d6\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerC7NM1d6\appAppKernelProdContainer([
    'container.build_hash' => 'C7NM1d6',
    'container.build_id' => '359ff675',
    'container.build_time' => 1720806329,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7NM1d6');
