<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNuEwT86\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNuEwT86/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNuEwT86.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerNuEwT86\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerNuEwT86\appAppKernelProdContainer([
    'container.build_hash' => 'NuEwT86',
    'container.build_id' => '0afc50ac',
    'container.build_time' => 1720544817,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNuEwT86');
